### ISSUE TITLE
Hint for setting default Website/StoreView

### ISSUE THREAD

**Issue by winkelsdorf** [yireo/Yireo_ProductTemplates#3]
Hi,

I am currently trying to set the default Website / StoreView for new products via ProductTemplates.

I was thinking of something like

``` code
<?xml version="1.0"?>
<product>
    <status>1</status>
    <tax_class_id>1</tax_class_id>
    <weight>0</weight>
    <meta_autogenerate>1</meta_autogenerate>
    <websites>Main Website</websites> <?-- which key sets the default website? -->
</product>
```

Do you have a hint?

**Comment by yireo** [comment]
Thanks for the suggestion. Actually, I would not do this by the name of a Website, but the ID. There would be multiple IDs possible as well. This has been added to the roadmap, though I can't say when this will be completed.

**Comment by winkelsdorf** [comment]
I tested before using IDs instead of Names, that was just to see if it would work. Ok, than I need to figure out how to do that. Anyway, thanks!
